import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import { notFound } from "next/navigation";

// Can be imported from a shared config
const locales = ["en", "de"];

export default function LocaleLayout({ children, params: { locale } }: any) {
  // if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className="bg-mainBackground text-white">{children}</body>
    </html>
  );
}
